<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="index.php">
            <i class="bi bi-house-door"></i> Dashboard
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="index.php?p=pages">
            <i class="bi bi-file-earmark"></i> Manage Pages
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="index.php?p=posts">
            <i class="bi bi-pencil-square"></i> Manage Posts
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="index.php?p=uploads">
            <i class="bi bi-cloud-upload"></i> Uploads
        </a>
    </li>
</ul>
