<div class="card mt-4 shadow-sm border border-light rounded-4">
  <div class="card-header bg-white d-flex justify-content-between align-items-center rounded-top-4">
    <div>
      <h6 class="mb-1 text-dark">
        <i class="bi bi-currency-dollar me-2 text-success"></i> Current AdSense Revenue
      </h6>
      <small class="text-muted">Your latest earnings</small>
    </div>
    <span class="badge bg-success-subtle text-success fw-semibold">Updated</span>
  </div>
  <div class="card-body">
    <p class="card-text text-muted">
      View your real-time AdSense earnings generated by your platform.
    </p>
    <h4 class="text-success">$153.75</h4>
    <p class="text-muted">Current month's revenue</p>
    <a href="#" class="btn btn-sm btn-outline-success mt-2">
      <i class="bi bi-bar-chart me-1"></i> View Revenue Insights
    </a>
  </div>
</div>
