            <li class="nav-item">
              <a href="index.php" class="nav-link active py-3 border-bottom rounded-0" title="Home"><i class="bi bi-house"></i></a>
            </li>
            <li>
              <a href="create_page.php" class="nav-link py-3 border-bottom rounded-0" title="Add page"><i class="bi bi-file-earmark-plus"></i></a>
            </li>
            <li>
              <a href="pages.php" class="nav-link py-3 border-bottom rounded-0" title="Edit page"><i class="bi bi-pencil-square"></i></a>
            </li>
            <li>
              <a href="create_post.php" class="nav-link py-3 border-bottom rounded-0" title="Add Post"><i class="bi bi-file-text"></i></a>
            </li>
            <li>
              <a href="posts.php" class="nav-link py-3 border-bottom rounded-0" title="Edit Post"><i class="bi bi-pencil"></i></a>
            </li>